name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit:
    name: unit / nodejs v${{ matrix.node-version }}
    uses: the-guild-org/shared-config/.github/workflows/ci-node-matrix.yml@main
    with:
      script: 'pnpm build && pnpm test:ci --logHeapUsage'
      nodeVersions: '[14,16,18]'
      packageManager: pnpm

  typecheck:
    runs-on: ubuntu-latest
    name: Type Check and ESM/CJS integrity checks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: Build Packages
        run: pnpm build

      - name: Typecheck
        run: pnpm run check

      # this fails right now cause in `types.ts` there is no JS to export
      # - name: Test ESM & CJS exports integrity
      #   run: pnpm bob check
