name: Release
on:
  push:
    branches:
      - master
jobs:
  stable:
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
    with:
      releaseScript: release
      releasePrName: Upcoming Release Changes (${{ github.ref }})
      nodeVersion: 18
      packageManager: pnpm
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}

  algolia:
    uses: the-guild-org/shared-config/.github/workflows/algolia-publish.yml@main
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      algoliaAppId: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
      algoliaAdminApiKey: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      algoliaIndexName: ${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }}
    with:
      domain: https://www.the-guild.dev/graphql/shield/
      source: 'Shield'
      packageManager: pnpm
